# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8ea796df9d68ca972fb81cbd9d32d82ca083b383ddc8665c43e5d79dfe3324fe8a5ecaeb318ae062f3091583ec08c42cd708f6756f44a6c71a077a8dcfa33c65

test:
  secret_key_base: 322bcbec67d15c79b370e10e45685ff6c625ec6c7871ec0f17278c40659457210ae42dd8315edb0075894fcef2d4bc5ef31e7a2ef0eaf4b52c2420bd7fb1db1c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
